web/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views 
from .views import ProductDetailView
# from .views import cart_view, add_to_cart, remove_from_cart, update_cart_item
from .views import BannerListView, BannerCreateView, BannerUpdateView, BannerDeleteView, WishlistListView,ProductListView,ProductCreateView,ProductUpdateView,ProductDeleteView

app_name = 'web'


urlpatterns = [
    path("", views.IndexView.as_view(), name='index'),
    path("about/", views.AboutView.as_view(), name="about"),
     path('checkout/', views.checkout, name='checkout'),
    path("contact/",views.contact,name='contact'),
    
    path("blog/", views.BlogListView.as_view(), name="blog"),
    path('blog/<slug:slug>/',views.BlogDetailView.as_view(), name='blog-detail'),
    path("product-category/", views.ProductCategoryListView.as_view(), name="product_category"),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path("contact-us/", views.ContactusView.as_view(), name="contact-us"),
    path('category-list/', views.categorylistdView.as_view(), name='category-list'),
    # path('products/', views.ProductsAddlView.as_view(), name='add_products'),
    path("product_list/",views.ProductsListView.as_view(), name="product_list"),
    path('product-detail/<slug:slug>/',ProductDetailView.as_view(), name='product_detail'),
    path('login/', views.user_login, name='login'),    
    path("admin-dashboard/product/add/", views.AddProductAdminView.as_view(), name="add_product"),
    path("admin-dashboard/product/list/", views.ProductListView.as_view(), name="list_product"),
    path("faq/",views.FAQView.as_view(), name='faq'),
    #dashbord
    path('banners/from/', views.banner_form, name='banner_form'),
    path('banners/', BannerListView.as_view(), name='banner_list'),
    path('banners/new/', BannerCreateView.as_view(), name='banner_create'),
    path('banners/<int:pk>/edit/', BannerUpdateView.as_view(), name='banner_update'),
    path('banners/<int:pk>/delete/', BannerDeleteView.as_view(), name='banner_delete'),
    # dashbord_product
    # Product URLs

    # path('products/', ProductListView.as_view(), name='product_list'),
    path('products/new/', ProductCreateView.as_view(), name='product_create'),
    path('products/<slug:slug>/edit/', ProductUpdateView.as_view(), name='product_update'),
    path('products/<slug:slug>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path("admin-dashboard/product/list/", views.ProductListView.as_view(), name="product_listedd"),
    #cart
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/', views.CartAddView.as_view(), name='add_cart'),
    path('cart-item-clear/<str:item_id>/', views.ClearCartItemView.as_view(), name='clear_cart_item'),
    path('cart/minus/', views.MinusToCartView.as_view(), name='minus_to_cart'),
    path('cart-clear/', views.ClearCartView.as_view(), name='clear_cart'),
    #wishlist
    path("wishlist/", views.WishlistListView.as_view(), name="wishlist"),
    path("wishlist/add/",views.AddToWishlistView.as_view(),name="add_to_wishlist"),
    path("wishlist/remove/<int:product_id>/",views.RemoveFromWishlistView.as_view(),name="remove_from_wishlist"),
   
]

woodberg/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
app_name = 'web'
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("web.urls", namespace="web")), 
    path("accounts/", include("registration.backends.simple.urls")),
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

web/views.py
from decimal import Decimal
from typing import Any
import urllib.parse
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.generic import TemplateView,ListView,CreateView
from django.views.generic import DetailView
from django.urls import reverse, reverse_lazy
from . models import Banner,Testimonial,Blog,Product, ProductCategory,Wishlist
from django.shortcuts import render, get_object_or_404
from .models import Product,Offer
from django.views.generic import View, RedirectView
from django.contrib.auth import authenticate, login
from .forms import LoginForm,ContactForm,CheckoutForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from .cart import Cart

from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Banner,Review
from .forms import BannerForm,ProductForm,ReviewForm
# Create your views here.

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                # Redirect to a success page
                return redirect('web:dashboard')
    else:
        form = LoginForm()
    return render(request, 'web/dashboard/login.html', {'form': form})




class IndexView(TemplateView):
    template_name = 'web/index.html'
    context_object_name = 'categories'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        banners = Banner.objects.all()
        blogs = Blog.objects.all()[:3]
        products = Product.objects.all()
        offers = Offer.objects.all()
        reviews = Review.objects.all()  # Fetch all reviews
        categories = ProductCategory.objects.all()[:10]

        context["banners"] = banners
        context["blogs"] = blogs
        context["products"] = products
        context["categories"] = categories
        context["offers"] = offers
        context["reviews"] = reviews
        
        # Group products by category
        category_products = {
            category: products.filter(category=category) for category in categories
        }
        context["category_products"] = category_products

        return context

    

class AboutView(TemplateView):

    template_name = 'web/about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        testimonials = Testimonial.objects.all()
        categories = ProductCategory.objects.all()
        context["categories"] = categories
        context["testimonials"] = testimonials
        
        return context

def checkout(request):
    if request.method == "POST":
        form = CheckoutForm(request.POST)
        if form.is_valid():
            form.save()
            response_data = {
                "status": "true",
                "title": "Successfully Submitted",
                "message": "Message successfully updated",
            }
            return JsonResponse(response_data)
        else:
            print(form.errors)
            response_data = {"status": "false", "title": "Form validation error"}
            return JsonResponse(response_data)
    else:
        initial_data = {'interest': 'dealership'}  # Define your initial data here
        form = CheckoutForm(initial=initial_data)  # Pass initial data to the form

        # Fetch product categories and testimonials
        categories = ProductCategory.objects.all()

        context = {
            "form": form,
            "categories": categories,  # Add categories to the context
        }
        return render(request, "web/checkout.html", context)


class ContactView(TemplateView):
    template_name = 'web/contact.html'  


class ContactusView(TemplateView):
    template_name = 'web/dashboard/contact-us.html'  


class WishlistListView(LoginRequiredMixin, ListView):
    model = Wishlist
    template_name = "web/wishlist.html"
    context_object_name = "wishlist_items"
    paginate_by = 10

    def get_queryset(self):
        return Wishlist.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = ProductCategory.objects.all()
        context["categories"] = categories
        return context


class AddToWishlistView( View):
    def get(self, request):
        if not request.user.is_authenticated:
            return JsonResponse({'message': 'User not authenticated'}, status=401)
        user = self.request.user
        product_id = request.GET.get("product_id",'')
        product = get_object_or_404(Product, pk=product_id)
        if not Wishlist.objects.filter(user=user, product=product).exists():
            # Create a new Wishlist object
            Wishlist.objects.create(
                user=user,
                product=product
            )
            return JsonResponse({'message': 'Product Added from Wishlist successfully','wishlist_count':Wishlist.objects.filter(user=request.user).count()})
        else:
            return JsonResponse({'message': 'Product is already in the Wishlist.','alreadyInWishlist': True})


class RemoveFromWishlistView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        product_id = self.kwargs.get("product_id")
        user = self.request.user

        wishlist_item = get_object_or_404(Wishlist, user=user, product_id=product_id)
        wishlist_item.delete()

        return redirect("web:wishlist")




    


class BlogListView(TemplateView):
    template_name = 'web/blog_list.html' 

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        blogs   = Blog.objects.all()
        categories = ProductCategory.objects.all()

        context["categories"] = categories
        context["blogs"] = blogs
        return context

class ProductsListView(ListView):
    model = Product
    template_name = 'web/products_list.html'
    context_object_name = "products"

    def get_queryset(self):
        queryset = super().get_queryset()
        category_slug = self.request.GET.get('category')
        if category_slug:
            queryset = queryset.filter(category__slug=category_slug)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = ProductCategory.objects.all()
        context['selected_category'] = self.request.GET.get('category')
        
        # Fetch all reviews and add to the context
        context['reviews'] = Review.objects.all()
        
        return context



# class ProductsAddlView(CreateView):
#     model = Product 
#     template_name = 'web/products.html'
#     fields = ['name', 'description', 'price', 'category']
#     success_url = reverse_lazy("web:cart.html")




# class ProductDetailView(TemplateView):
#     template_name = 'web/product_detail.html'

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         slug = self.kwargs.get('slug')
#         products = get_object_or_404(Product, slug=slug)
#         categories = ProductCategory.objects.all()
        
#         other_products = Product.objects.exclude(slug=slug)
#         context['products'] = products
#         context['other_products'] = other_products
#         context["categories"] = categories
        
#         return context

class ProductDetailView(DetailView):
    model = Product
    template_name = "web/product_detail.html"
    context_object_name = "product"
    slug_field = 'slug'
    slug_url_kwarg = 'slug'

    def get_context_data(self, **kwargs):
        # Ensure self.object is set by calling self.get_object()
        self.object = self.get_object()
        context = super().get_context_data(**kwargs)
        product = self.object  # Use self.object instead of calling self.get_object() again
        context['other_products'] = Product.objects.exclude(slug=product.slug)
        context['form'] = ReviewForm()

        # Fetch reviews related to the product
        context['reviews'] = product.reviews.filter(is_active=True).order_by('-created_at')
        return context

    def post(self, request, *args, **kwargs):
        product = self.get_object()
        form = ReviewForm(request.POST)
        
        if form.is_valid():
            review = form.save(commit=False)
            review.product = product
            review.save()
            
            response_data = {
                "status": "true",
                "title": "Successfully Submitted",
                "message": "Review successfully submitted",
            }
            return JsonResponse(response_data)
        else:
            response_data = {
                "status": "false",
                "title": "Form validation error",
                "errors": form.errors,
            }
            print(form.errors)
            return JsonResponse(response_data, status=400)
        

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)
         
      



class BlogDetailView(DetailView):
    model = Blog
    template_name = 'web/blog-detail.html'  # Assuming you have a template for blog detail

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        blogs = Blog.objects.all()
        slug = self.kwargs.get('slug')  # Get slug from URL parameters
        blogs = get_object_or_404(Blog, slug=slug)
        categories = ProductCategory.objects.all()
        other_blogs = Blog.objects.exclude(slug=slug)

        context["blogs"] = blogs

templates/web/checkout.html
{% extends "web/base.html" %}
{% load static %}
{% block content %}
<div class="page-wrapper">


	<main class="main">
		<div class="page-header text-center"
			style="background-image: url('static/web/assets/images/page-header-bg.jpg')">
			<div class="container">
				<h1 class="page-title">Checkout<span>Shop</span></h1>
			</div><!-- End .container -->
		</div><!-- End .page-header -->
		<nav aria-label="breadcrumb" class="breadcrumb-nav">

			<div class="container">
				<ol class="breadcrumb">
					<li class="breadcrumb-item"><a href="{% url "web:index" %}">Home</a></li>
					<li class="breadcrumb-item"><a href="#">Shop</a></li>
					<li class="breadcrumb-item active" aria-current="page">Checkout</li>
				</ol>
			</div><!-- End .container -->
		</nav><!-- End .breadcrumb-nav -->

		<div class="page-content">
			<div class="checkout contact-form-wrap" data-aos="fade-up" data-aos-delay="200">
				<div class="container">
					<div class="checkout-discount">
					</div><!-- End .checkout-discount -->

					<form class="contact-form-style ajax reload" id="contact-form" method="post">
						{% csrf_token %}
						<div class="row">
							<div class="col-lg-9">
								<h2 class="checkout-title">Billing Details</h2><!-- End .checkout-title -->
								<div class="row">
									<div class="col-sm-6">
										<label>First Name *</label>
										{{ form.first_name }}
									</div><!-- End .col-sm-6 -->

									<div class="col-sm-6">
										<label>Last Name *</label>
										{{ form.last_name }}
									</div><!-- End .col-sm-6 -->
								</div><!-- End .row -->

								<label>Street address *</label>
								{{ form.street_address }}

								<div class="row">
									<div class="col-sm-6">
										<label>City </label>
										{{ form.city }}
									</div><!-- End .col-sm-6 -->

									<div class="col-sm-6">
										<label>State</label>
										{{ form.state }}
									</div><!-- End .col-sm-6 -->
								</div><!-- End .row -->

								<div class="row">
									<div class="col-sm-6">
										<label>Pincode</label>
										{{ form.pincode }}
									</div><!-- End .col-sm-6 -->

									<div class="col-sm-6">
										<label>Phone *</label>
										{{ form.mobil }}
									</div><!-- End .col-sm-6 -->
								</div><!-- End .row -->

								<label>Email address *</label>
								{{ form.email }}

								{% comment %} <div class="custom-control custom-checkbox">
									<input type="checkbox" class="custom-control-input" id="checkout-create-acc">
									<label class="custom-control-label" for="checkout-create-acc">Create an
										account?</label>
								</div><!-- End .custom-checkbox -->

								<div class="custom-control custom-checkbox">
									<input type="checkbox" class="custom-control-input" id="checkout-diff-address">
									<label class="custom-control-label" for="checkout-diff-address">Ship to a different
										address?</label>
								</div><!-- End .custom-checkbox --> {% endcomment %}

								<label>Order notes (optional)</label>
								<textarea class="form-control" cols="30" rows="4"
									placeholder="Notes about your order, e.g. special notes for delivery"></textarea>
							</div><!-- End .col-lg-9 -->
							<aside class="col-lg-3">
								<div class="summary">
									<h3 class="summary-title">Your Order</h3><!-- End .summary-title -->


									<table class="table table-summary">
										<thead>
											<tr>
												<th>Product</th>
												<th>Total</th>
											</tr>
										</thead>

										<tbody>
											{% for item in items %}
											<tr>
												<td><a href="#">{{item.product.name}}</a></td>
												<td>₹ {{item.product.price}}</td>
											</tr>
											{% endfor %}


											<tr class="summary-subtotal">
												<td>Subtotal:</td>
												<td>$160.00</td>
											</tr><!-- End .summary-subtotal -->
											<tr>
												<td>Shipping:</td>
												<td>Free shipping</td>
											</tr>
											<tr class="summary-total">
												<td>Total:</td>
												<td>$160.00</td>
											</tr><!-- End .summary-total -->
										</tbody>
									</table><!-- End .table table-summary -->


									<div class="accordion-summary" id="accordion-payment">
									

										<div class="card">
											<div class="card-header" id="heading-2">
												<h2 class="card-title">
													<a class="collapsed" role="button" data-toggle="collapse"
														href="#collapse-2" aria-expanded="false"
														aria-controls="collapse-2">
														onlin payments
													</a>
												</h2>
											</div><!-- End .card-header -->
											<div id="collapse-2" class="collapse" aria-labelledby="heading-2"
												data-parent="#accordion-payment">
												<div class="card-body">
													Ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio.
													Quisque volutpat mattis eros. Nullam malesuada erat ut turpis.
												</div><!-- End .card-body -->
											</div><!-- End .collapse -->
										</div><!-- End .card -->

										<div class="card">
											<div class="card-header" id="heading-3">
												<h2 class="card-title">
													<a class="collapsed" role="button" data-toggle="collapse"
														href="#collapse-3" aria-expanded="false"
														aria-controls="collapse-3">
														Cash on delivery
													</a>
												</h2>
											</div><!-- End .card-header -->
											<div id="collapse-3" class="collapse" aria-labelledby="heading-3"
												data-parent="#accordion-payment">
												<div class="card-body">Quisque volutpat mattis eros. Lorem ipsum dolor
													sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat
													mattis eros.
												</div><!-- End .card-body -->
											</div><!-- End .collapse -->
										</div><!-- End .card -->
									</div><!-- End .accordion -->

									<button type="submit"
										class="btn btn-outline-primary-2 btn-order btn-block primary_btn">
										<span class="btn-text">Place Order</span>
										<span class="btn-hover-text">Proceed to Checkout</span>
									</button>
								</div><!-- End .summary -->
							</aside><!-- End .col-lg-3 -->
						</div><!-- End .row -->
					</form>

				</div><!-- End .container -->
			</div><!-- End .checkout -->
		</div><!-- End .page-content -->
	</main><!-- End .main -->


</div><!-- End .page-wrapper -->
<button id="scroll-top" title="Back to Top"><i class="icon-arrow-up"></i></button>

<!-- Mobile Menu -->
<div class="mobile-menu-overlay"></div><!-- End .mobil-menu-overlay -->




<!-- Plugins JS File -->
{% endblock %}

templates/web/contact.html
{% extends "web/base.html" %}
{% load static %}
{% block content %}

    <div class="page-wrapper">
      

        <main class="main">
        	<div class="page-header text-center" style="background-image: url({% static 'web/assets/images/page-header-bg.jpg'%})">
        		<div class="container">
        			<h1 class="page-title">Contact us<span>Pages</span></h1>
        		</div><!-- End .container -->
        	</div><!-- End .page-header -->
            <nav aria-label="breadcrumb" class="breadcrumb-nav border-0 mb-0">
                <div class="container">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url "web:index" %}">Home</a></li>
                        <li class="breadcrumb-item"><a href="#">Pages</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Contact us </li>
                    </ol>
                </div><!-- End .container -->
            </nav><!-- End .breadcrumb-nav -->

            <div class="container-fluid">
                <div class="map pt-120 map_bm" data-aos="fade-up" data-aos-delay="200">
                    <iframe class="map_hr" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3914.5808436691786!2d75.94623757481051!3d11.144562489027512!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ba64f55b34e88fd%3A0x751f7dc376719af2!2sBrandmarker%20Branding%20%26%20Digital%20Marketing!5e0!3m2!1sen!2sin!4v1717762841108!5m2!1sen!2sin" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>            </div>
                </div>
            </div>
                  
                <div class="container">
                	<div class="row">
                		<div class="col-md-4">
                			<div class="contact-box text-center">
        						<h3>Office</h3>

        						<address>Chundakkadan's Vattuparambu, Kondotty (PO)  <br>Malappuram Dt., Kerala, India</address>
        					</div><!-- End .contact-box -->
                		</div><!-- End .col-md-4 -->

                		<div class="col-md-4">
                			<div class="contact-box text-center">
        						<h3>Start a Conversation</h3>  

        						<div><a href="salmanulfarizz7909@gmail.com"><span class="__cf_email__" data-cfemail="">[email&#160;protected]</span></a></div>
        						<div><a href="tel:#">+91 892-128-33351</a>, <a href="tel:#">+91 892-128-33351</a></div>
        					</div><!-- End .contact-box -->
                		</div><!-- End .col-md-4 -->
                       

                		<div class="col-md-4">
                			<div class="contact-box text-center">
        						<h3>Social</h3>

        						<div class="social-icons social-icons-color justify-content-center">
			    					<a href="https://www.facebook.com/profile.php?id=61560420112322" class="social-icon social-facebook" title="Facebook" target="_blank"><i class="icon-facebook-f"></i></a>
			    					<a href="#" class="social-icon social-twitter" title="Twitter" target="_blank"><i class="icon-twitter"></i></a>
			    					<a href="https://www.instagram.com/heartima_pickles/" class="social-icon social-instagram" title="Instagram" target="_blank"><i class="icon-instagram"></i></a>
			    					{% comment %} <a href="#" class="social-icon social-youtube" title="Youtube" target="_blank"><i class="icon-youtube"></i></a> {% endcomment %}
			    				</div><!-- End .soial-icons -->
        					</div><!-- End .contact-box -->
                		</div><!-- End .col-md-4 -->
                	</div><!-- End .row -->

                	<hr class="mt-3 mb-5 mt-md-1">
                	<div class="touch-container row justify-content-center">
                		<div class="col-md-9 col-lg-7">
                			<div class="text-center">
                			<h2 class="title mb-1">Get In Touch</h2><!-- End .title mb-2 -->
                			<p class="lead text-primary">
                                Chundakkadan's Vattuparambu,
                                Kondotty (PO) Malappuram
                                Dt., Kerala, India"                			</p><!-- End .lead text-primary -->
                			<p class="mb-3">Manufactured by: Chundakkadan's Vattuparambu,
                                Kondotty (PO) Malappuram
                                Dt., Kerala, India"</p>
                			</div><!-- End .text-center -->
                            <form class="contact-form mb-2 " method="post">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-sm-4">
                                        <label for="cname" class="sr-only">Name</label>
                                        {{form.name}}
                                    </div><!-- End .col-sm-4 -->
                            
                                    <div class="col-sm-4">
                                        <label for="cemail" class="sr-only">Email</label>
                                        {{form.email}}
                                    </div><!-- End .col-sm-4 -->
                            
                                    <div class="col-sm-4">
                                        <label for="cphone" class="sr-only">Phone</label>
                                        {{form.phone}}
                                    </div><!-- End .col-sm-4 -->
                                </div><!-- End .row -->
                            
                                <label for="csubject" class="sr-only">Subject</label>
                                {{form.subject}}
                                <label for="cmessage" class="sr-only">Message</label>
                                {{form.message}}
                                
                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary btn-minwidth-sm">
                                        <span>SUBMIT</span>
                                        <i class="icon-long-arrow-right"></i>
                                    </button>
                                </div><!-- End .text-center -->
                            </form><!-- End .contact-form -->
                            
                		</div><!-- End .col-md-9 col-lg-7 -->
                	</div><!-- End .row -->
                </div><!-- End .container -->
            </div><!-- End .page-content -->
        </main><!-- End .main -->

    </div><!-- End .page-wrapper -->
    <button id="scroll-top" title="Back to Top"><i class="icon-arrow-up"></i></button>

    <!-- Mobile Menu -->
 

    

    <!-- Sign in / Register Modal -->
    
    <!-- Google Map -->

    <!-- Plugins JS File -->
    {% endblock %}

templates/web/product-category.html
{% extends "web/base.html" %}
{% load static %}
{% block content %}
    <div class="page-wrapper">
      
        <main class="main">
        	<div class="page-header text-center" style="background-image: url('assets/images/page-header-bg.jpg'%}')">
        		<div class="container">
        			<h1 class="page-title">Product Category<span></span></h1>
        		</div><!-- End .container -->
        	</div><!-- End .page-header -->
            <nav aria-label="breadcrumb" class="breadcrumb-nav">
                <div class="container">
                    <ol class="breadcrumb">
                    </ol>
                </div><!-- End .container -->
            </nav><!-- End .breadcrumb-nav -->

            <div class="page-content">
                <div class="container">
                	<h2 class="title text-center mb-3"></h2><!-- End .title mb-2 -->

                	<div class="row">
                		<div class="col-md-6">
                			<div class="banner banner-cat">
	                			<a href="{% url "web:product" %}">
	                				<img src="{%static 'web/assets/images/category/banner-1.jpg'%}" alt="Banner">
	                			</a>

	                			<div class="banner-content">
	                				<h3 class="banner-title">SOFA</h3><!-- End .banner-title -->
	                				<h4 class="banner-subtitle">18 Products</h4><!-- End .banner-subtitle -->
	                				<a href="{% url "web:product" %}" class="banner-link">Shop Now</a>
	                			</div><!-- End .banner-content -->
                			</div><!-- End .banner -->
                		</div><!-- End .col-md-6 -->

                		<div class="col-md-6">
                			<div class="banner banner-cat">
	                			<a href="{% url "web:product" %}">
	                				<img src="{%static 'web/assets/images/category/banner-2.jpg'%}" alt="Banner">
	                			</a>

	                			<div class="banner-content">
	                				<h3 class="banner-title">chairs</h3><!-- End .banner-title -->
	                				<h4 class="banner-subtitle">12 Products</h4><!-- End .banner-subtitle -->
	                				<a href="{% url "web:product" %}" class="banner-link">Shop Now</a>
	                			</div><!-- End .banner-content -->
                			</div><!-- End .banner -->
                		</div><!-- End .col-md-6 -->
                	</div><!-- End .row -->
                    <div class="row">
                		<div class="col-md-6">
                			<div class="banner banner-cat">
	                			<a href="{% url "web:product" %}">
	                				<img src="{%static 'web/assets/images/category/banner-1.jpg'%}" alt="Banner">
	                			</a>

	                			<div class="banner-content">
	                				<h3 class="banner-title">bed</h3><!-- End .banner-title -->
	                				<h4 class="banner-subtitle">18 Products</h4><!-- End .banner-subtitle -->
	                				<a href="{% url "web:product" %}" class="banner-link">Shop Now</a>
	                			</div><!-- End .banner-content -->
                			</div><!-- End .banner -->
                		</div><!-- End .col-md-6 -->

                		<div class="col-md-6">
                			<div class="banner banner-cat">
	                			<a href="{% url "web:product" %}">
	                				<img src="{%static 'web/assets/images/category/banner-2.jpg'%}" alt="Banner">
	                			</a>

	                			<div class="banner-content">
	                				<h3 class="banner-title">wardrobes</h3><!-- End .banner-title -->
	                				<h4 class="banner-subtitle">12 Products</h4><!-- End .banner-subtitle -->
	                				<a href="{% url "web:product" %}" class="banner-link">Shop Now</a>
	                			</div><!-- End .banner-content -->
                			</div><!-- End .banner -->
                		</div><!-- End .col-md-6 -->
                	</div><!-- End .row -->
                </div><!-- End .container -->                	
           </div><!-- End .container -->
            </div><!-- End .page-content -->

            <!-- Elements list -->
            
        </main><!-- End .main -->

       
    </div><!-- End .page-wrapper -->
    <button id="scroll-top" title="Back to Top"><i class="icon-arrow-up"></i></button>

    <!-- Mobile Menu -->
    <div class="mobile-menu-overlay"></div><!-- End .mobil-menu-overlay -->


    <!-- Sign in / Register Modal -->
   

{% endblock %}