web/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views 
from .views import ProductDetailView
# from .views import cart_view, add_to_cart, remove_from_cart, update_cart_item
from .views import BannerListView, BannerCreateView, BannerUpdateView, BannerDeleteView, WishlistListView,ProductListView,ProductCreateView,ProductUpdateView,ProductDeleteView

app_name = 'web'


urlpatterns = [
    path("", views.IndexView.as_view(), name='index'),
    path("about/", views.AboutView.as_view(), name="about"),
     path('checkout/', views.checkout, name='checkout'),
    path("contact/",views.contact,name='contact'),
    
    path("blog/", views.BlogListView.as_view(), name="blog"),
    path('blog/<slug:slug>/',views.BlogDetailView.as_view(), name='blog-detail'),
    path("product-category/", views.ProductCategoryListView.as_view(), name="product_category"),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path("contact-us/", views.ContactusView.as_view(), name="contact-us"),
    path('category-list/', views.categorylistdView.as_view(), name='category-list'),
    # path('products/', views.ProductsAddlView.as_view(), name='add_products'),
    path("product_list/",views.ProductsListView.as_view(), name="product_list"),
    path('product-detail/<slug:slug>/',ProductDetailView.as_view(), name='product_detail'),
    path('login/', views.user_login, name='login'),    
    path("admin-dashboard/product/add/", views.AddProductAdminView.as_view(), name="add_product"),
    path("admin-dashboard/product/list/", views.ProductListView.as_view(), name="list_product"),
    path("faq/",views.FAQView.as_view(), name='faq'),
    #dashbord
    path('banners/from/', views.banner_form, name='banner_form'),
    path('banners/', BannerListView.as_view(), name='banner_list'),
    path('banners/new/', BannerCreateView.as_view(), name='banner_create'),
    path('banners/<int:pk>/edit/', BannerUpdateView.as_view(), name='banner_update'),
    path('banners/<int:pk>/delete/', BannerDeleteView.as_view(), name='banner_delete'),
    # dashbord_product
    # Product URLs

    # path('products/', ProductListView.as_view(), name='product_list'),
    path('products/new/', ProductCreateView.as_view(), name='product_create'),
    path('products/<slug:slug>/edit/', ProductUpdateView.as_view(), name='product_update'),
    path('products/<slug:slug>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path("admin-dashboard/product/list/", views.ProductListView.as_view(), name="product_listedd"),
    #cart
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/', views.CartAddView.as_view(), name='add_cart'),
    path('cart-item-clear/<str:item_id>/', views.ClearCartItemView.as_view(), name='clear_cart_item'),
    path('cart/minus/', views.MinusToCartView.as_view(), name='minus_to_cart'),
    path('cart-clear/', views.ClearCartView.as_view(), name='clear_cart'),
    #wishlist
    path("wishlist/", views.WishlistListView.as_view(), name="wishlist"),
    path("wishlist/add/",views.AddToWishlistView.as_view(),name="add_to_wishlist"),
    path("wishlist/remove/<int:product_id>/",views.RemoveFromWishlistView.as_view(),name="remove_from_wishlist"),
   
]

woodberg/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
app_name = 'web'
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("web.urls", namespace="web")), 
    path("accounts/", include("registration.backends.simple.urls")),
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/web/partials/footer.html
{% load static %}
<footer class="footer footer-2">
   


    <div class="footer-middle">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-lg-6">
                    <div class="widget widget-about">
                        <img src="{% static 'web/assets/images/logo-4.png'%}" class="footer-logo" alt="Footer Logo" width="105" height="25">
                        <p>Manufactured by: Chundakkadan's Vattuparambu,<br> Kondotty (PO) Malappuram <br>Dt., Kerala, India" </p>
                        
                        <div class="widget-about-info">
                            <div class="row">
                                <div class="col-sm-6 col-md-4">
                                    <span class="widget-about-title">Got Question? Call us 24/7</span>
                                    <a href="tel:">+91 89 212 8333 51</a>
                                </div><!-- End .col-sm-6 -->
                                <div class="col-sm-6 col-md-8">
                                    <span class="widget-about-title">Payment Method</span>
                                    <figure class="footer-payments">
                                        <img src="{% static 'web/assets/images/payments.png'%}" alt="Payment methods" width="272" height="20">
                                    </figure><!-- End .footer-payments -->
                                </div><!-- End .col-sm-6 -->
                            </div><!-- End .row -->
                        </div><!-- End .widget-about-info -->
                    </div><!-- End .widget about-widget -->
                </div><!-- End .col-sm-12 col-lg-3 -->

                <div class="col-sm-4 col-lg-2">
                    <div class="widget">
                        <h4 class="widget-title">Information</h4><!-- End .widget-title -->

                        <ul class="widget-list">
                            <li><a href="{% url "web:about" %}">About Heartima </a></li>
                            <li><a href="{% url "web:faq" %}">How to shop on Heartima </a></li>
                            <li><a href="{% url "web:faq" %}">FAQ</a></li>
                            <li><a href="{% url "web:contact" %}">Contact us</a></li>
                            
                        </ul><!-- End .widget-list -->
                    </div><!-- End .widget -->
                </div><!-- End .col-sm-4 col-lg-3 -->

                <div class="col-sm-4 col-lg-2">
                    <div class="widget">
                        <h4 class="widget-title">Customer Service</h4><!-- End .widget-title -->

                        <ul class="widget-list">
                            <li><a href="{% url "web:faq" %}">Payment Methods</a></li>
                            <li><a href="{% url "web:faq" %}">Money-back guarantee!</a></li>
                            <li><a href="{% url "web:faq" %}">Returns</a></li>
                            <li><a href="{% url "web:faq" %}">Shipping</a></li>
                            <li><a href="{% url "web:faq" %}">Terms and conditions</a></li>
                            <li><a href="{% url "web:faq" %}">Privacy Policy</a></li>
                        </ul><!-- End .widget-list -->
                    </div><!-- End .widget -->
                </div><!-- End .col-sm-4 col-lg-3 -->

                <div class="col-sm-4 col-lg-2">
                    <div class="widget">
                        <h4 class="widget-title">page</h4><!-- End .widget-title -->

                        <ul class="widget-list">
                            <li><a href="{% url "web:product_list" %}">products</a></li>
                            <li><a href="{% url "web:cart" %}">View Cart</a></li>
                            <li><a href="{% url "web:wishlist" %}">My Wishlist</a></li>
                    
                            <li><a href="{% url "web:contact" %}">Help</a></li>
                        </ul><!-- End .widget-list -->
                    </div><!-- End .widget -->
                </div><!-- End .col-sm-64 col-lg-3 -->
            </div><!-- End .row -->
        </div><!-- End .container -->
    </div><!-- End .footer-middle -->

    <div class="footer-bottom">
        <div class="container">
            <p class="footer-copyright">© 2024 <a href="http://www.brandmarker.in">brandmarker</a> - Developed by Brand Marker </p><!-- End .footer-copyright -->
            <ul class="footer-menu">
 
            </ul><!-- End .footer-menu -->

            <div class="social-icons social-icons-color">
                <span class="social-label">Social Media</span>
                <a href="https://www.facebook.com/profile.php?id=61560420112322" class="social-icon social-facebook" title="Facebook" target="_blank"><i class="icon-facebook-f"></i></a>
                <a href="#" class="social-icon social-twitter" title="Twitter" target="_blank"><i class="icon-twitter"></i></a>
                <a href="https://www.instagram.com/heartima_pickles/" class="social-icon social-instagram" title="Instagram" target="_blank"><i class="icon-instagram"></i></a>
                {% comment %} <a href="#" class="social-icon social-youtube" title="Youtube" target="_blank"><i class="icon-youtube"></i></a> {% endcomment %}
            </div><!-- End .soial-icons -->
        </div><!-- End .container -->
    </div><!-- End .footer-bottom -->
</footer><!-- End .footer -->

templates/web/partials/header.html
{% load static %}


<header class="header">
    <div class="header-top">
        <div class="container">
            <div class="header-left">
                <div class="header-dropdown">
                 
                    <div class="header-menu">
                       
                    </div><!-- End .header-menu -->
                </div><!-- End .header-dropdown -->

                <div class="header-dropdown">
                  <p> All are  welcome</p>
                </div><!-- End .header-dropdown -->
            </div><!-- End .header-left -->

            <div class="header-right">
                <ul class="top-menu">
                    <li>
                        <a href="#">Links</a>
                        <ul>
                            <li><a href="tel:#"><i class="icon-phone"></i>Call:+91 89 212 8333 51</a></li>
                            <li><a href="{% url 'web:wishlist' %}"><i class="icon-heart-o"></i>Wishlist <span>( {{ wishlist_count }})</span></a></li>
                            <li><a href="{% url "web:about" %}">About Us</a></li>
                            <li><a href="{% url "web:contact" %}">Contact Us</a></li>
                            
                        </ul>
                    </li>
                </ul><!-- End .top-menu -->
            </div><!-- End .header-right -->
        </div><!-- End .container -->
    </div><!-- End .header-top -->

    <div class="header-middle sticky-header">
        <div class="container">
            <div class="header-left">
                <button class="mobile-menu-toggler">
                    <span class="sr-only">Toggle mobile menu</span>
                    <i class="icon-bars"></i>
                </button>
                <a href="{% url "web:index" %}" class="logo">
                    <img src="{% static 'web/assets/images/logo-4.png' %}" alt="Molla Logo" width="105" height="50">
                </a>

                <nav class="main-nav">
                    <ul class="menu sf-arrows">
                        <li class="megamenu-container active">
                            <a href="{% url "web:index" %}" class="">Home</a>  
                        </li>
                        <li>
                            <a href="{% url "web:product_list" %}" class="">COLLECTIONS </a>
                            {% comment %} <div class="megamenu ">
                                <div class="row no-gutters">
                                    <div class="col-md-8">
                                        <div class="menu-col">
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="menu-title">Shop with sidebar</div><!-- End .menu-title -->
                                                    <ul>
                                                        <li><a href=""></a></li>
                                                        <li><a href="category-2cols.html">Shop Grid 2 Columns</a></li>
                                                        <li><a href="category.html">Shop Grid 3 Columns</a></li>
                                                        <li><a href="category-4cols.html">Shop Grid 4 Columns</a></li>
                                                        
                                                    </ul>
                                            </div><!-- End .row -->
                                        </div><!-- End .menu-col -->
                                    </div><!-- End .col-md-8 -->

                                  
                                </div><!-- End .row -->
                            </div><!-- End .megamenu megamenu-md --> {% endcomment %}
                        </li>
                        <li>
                            <a href="{% url "web:about" %}" class="">ABOUT US</a>

                        </li>
                        <li>
                            <a href="#" class="sf-with-ul">Pickle </a>

                            <ul>
                                {% for category in categories %}
                                <li>
                                    <a href="{% url 'web:product_list' %}?category={{ category.slug }}" class="">{{ category.name }}</a>
                                </li>
                                {% endfor %}
                      
                           
                            </ul>
                        </li>
                        <li>
                            <a href="#" class="sf-with-ul">CATALOGUE</a>
{% comment %} 
                            <ul>
                                <li><a href="#">Classic</a></li>
                                <li><a href="#">Listing</a></li>
                                
                                
                                </li>
                            </ul> {% endcomment %}
                        </li>
                        <li>
                            <a href="{% url "web:contact" %}" class="">CONTACT</a>

                        </li>
                    </ul><!-- End .menu -->
                </nav><!-- End .main-nav -->
            </div><!-- End .header-left -->

            <div class="header-right">
                <div class="header-search">
      
                    <form action="#" method="get">
                        <div class="header-search-wrapper">
                            <label for="q" class="sr-only">Search</label>
                            <input type="search" class="form-control" name="q" id="q" placeholder="Search in..." required>
                        </div><!-- End .header-search-wrapper -->
                    </form>
                </div><!-- End .header-search -->
                <div class="dropdown compare-dropdown">
                    <a href="{% url "web:wishlist" %}" class="dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-display="static" title="Compare Products" aria-label="Compare Products">
                        <i class="icon-heart-o"> </i>
                        
                    </a>

                    <div class="dropdown-menu dropdown-menu-right">
                        <ul class="compare-products">
                            {% for item in wishlist_items %}
                            <li class="compare-product">
                                <a href="#" class="btn-remove" title="Remove Product"><i class="icon-close"></i></a>
                                <h4 class="compare-product-title"><a href="product.html">{{ item.name }}</a></h4>
                            </li>
                            {% endfor %}
                            
                        </ul>

                        <div class="compare-actions">
                            {% comment %} <a href="#" class="action-link">Clear All</a> {% endcomment %}
                            <a href="{% url "web:wishlist" %}" class="btn btn-outline-primary-2"><span>View Wishlist</span><i class="icon-long-arrow-right"></i></a>
                        </div>
                    </div><!-- End .dropdown-menu -->
                </div><!-- End .compare-dropdown -->

                <div class="dropdown cart-dropdown">
                    <a href="{% url 'web:cart' %}" class="dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-display="static">
                        <i class="icon-shopping-cart"></i>
                        <span class="cart-count">{{ cart_count }}</span>
                    </a>
                
                    <div class="dropdown-menu dropdown-menu-right">
                        <div class="dropdown-cart-products">
                            {% for item in cart_items %}
                            <div class="product">
                                <div class="product-cart-details">
                                    <h4 class="product-title">
                                        <a href="{{ product.get_absolute_url }}">{{ item.product.name }}</a>
                                    </h4>

                                    <span class="cart-product-info">
                                        <span class="cart-product-qty">{{ item.quantity }}</span>
                                        x {{ item.total_price }}
                                    </span>
                                </div><!-- End .product-cart-details -->

                                <figure class="product-image-container">
                                    <a href="{{ item.get_absolute_url }}" class="product-image">
                                        <img src="{{ item.product.image.url }}" alt="product">
                                    </a>
                                </figure>
                            </div><!-- End .product -->
                            {% endfor %}
                        </div><!-- End .dropdown-cart-products -->
                
                        <div class="dropdown-cart-total">
                            <span>Total</span>
                            <span class="cart-total-price">{{ cart_total }}</span>
                        </div><!-- End .dropdown-cart-total -->
                
                        <div class="dropdown-cart-action">
                            <a href="{% url 'web:cart' %}" class="btn btn-primary">View Cart</a>
                            <a href="{% url 'web:checkout' %}" class="btn btn-outline-primary-2"><span>Checkout</span><i class="icon-long-arrow-right"></i></a>
                        </div><!-- End .dropdown-cart-action -->
                    </div><!-- End .dropdown-menu -->
                </div><!-- End .dropdown cart-dropdown -->
    
                </div><!-- End .cart-dropdown -->
            </div><!-- End .header-right -->
        </div><!-- End .container -->
    </div><!-- End .header-middle -->
</header><!-- End .header -->

templates/web/partials/mobil_header.html
<div class="mobile-menu-container">
    <div class="mobile-menu-wrapper">
        <span class="mobile-menu-close"><i class="icon-close"></i></span>

        <form action="#" method="get" class="mobile-search">
            <label for="mobile-search" class="sr-only">Search</label>
            <input type="search" class="form-control" name="mobile-search" id="mobile-search" placeholder="Search in..." required>
            <button class="btn btn-primary" type="submit"><i class="icon-search"></i></button>
        </form>
        
        <nav class="mobile-nav">
            <ul class="mobile-menu">
                <li class="active">
                    <a href="{% url "web:index" %}">Home</a>
                </li>
                <li>
                    <a href="{% url "web:product_list" %}">COLLECTIONS </a>
                    
                </li>
                <li>
                    <a href="{% url "web:about" %}" class="">ABOUT US</a>
                   
                </li>
                <li>
                    <a href="{% url "web:product_list" %}">FURNITURE</a>
                    <ul>
                        {% for category in categories %}
                        <li>
                            <a href="{% url 'web:product_list' %}?category={{ category.slug }}" class="">{{ category.name }}</a>
                        </li>
                        {% endfor %}
                        <li>
                        </ul>
                        

                        </li>
                      
                    
                </li>
                <li>
                    <a href="#">CATALOGUE</a>

                    <ul>
                        <li><a href="#">Classic</a></li>
                        <li><a href="#">Listing</a></li>
                        
                       
                    </ul>
                </li>
                <li>
                    <a href="{% url "web:contact" %}">Contact</a>
                </li>
            </ul>
        </nav><!-- End .mobile-nav -->

        <div class="social-icons">
            <a href="#" class="social-icon" target="_blank" title="Facebook"><i class="icon-facebook-f"></i></a>
            <a href="#" class="social-icon" target="_blank" title="Twitter"><i class="icon-twitter"></i></a>
            <a href="#" class="social-icon" target="_blank" title="Instagram"><i class="icon-instagram"></i></a>
            <a href="#" class="social-icon" target="_blank" title="Youtube"><i class="icon-youtube"></i></a>
        </div><!-- End .social-icons -->
    </div><!-- End .mobile-menu-wrapper -->
</div><!-- End .mobile-menu-container -->