web/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views 
from .views import ProductDetailView
# from .views import cart_view, add_to_cart, remove_from_cart, update_cart_item
from .views import BannerListView, BannerCreateView, BannerUpdateView, BannerDeleteView, WishlistListView,ProductListView,ProductCreateView,ProductUpdateView,ProductDeleteView

app_name = 'web'


urlpatterns = [
    path("", views.IndexView.as_view(), name='index'),
    path("about/", views.AboutView.as_view(), name="about"),
     path('checkout/', views.checkout, name='checkout'),
    path("contact/",views.contact,name='contact'),
    
    path("blog/", views.BlogListView.as_view(), name="blog"),
    path('blog/<slug:slug>/',views.BlogDetailView.as_view(), name='blog-detail'),
    path("product-category/", views.ProductCategoryListView.as_view(), name="product_category"),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path("contact-us/", views.ContactusView.as_view(), name="contact-us"),
    path('category-list/', views.categorylistdView.as_view(), name='category-list'),
    # path('products/', views.ProductsAddlView.as_view(), name='add_products'),
    path("product_list/",views.ProductsListView.as_view(), name="product_list"),
    path('product-detail/<slug:slug>/',ProductDetailView.as_view(), name='product_detail'),
    path('login/', views.user_login, name='login'),    
    path("admin-dashboard/product/add/", views.AddProductAdminView.as_view(), name="add_product"),
    path("admin-dashboard/product/list/", views.ProductListView.as_view(), name="list_product"),
    path("faq/",views.FAQView.as_view(), name='faq'),
    #dashbord
    path('banners/from/', views.banner_form, name='banner_form'),
    path('banners/', BannerListView.as_view(), name='banner_list'),
    path('banners/new/', BannerCreateView.as_view(), name='banner_create'),
    path('banners/<int:pk>/edit/', BannerUpdateView.as_view(), name='banner_update'),
    path('banners/<int:pk>/delete/', BannerDeleteView.as_view(), name='banner_delete'),
    # dashbord_product
    # Product URLs

    # path('products/', ProductListView.as_view(), name='product_list'),
    path('products/new/', ProductCreateView.as_view(), name='product_create'),
    path('products/<slug:slug>/edit/', ProductUpdateView.as_view(), name='product_update'),
    path('products/<slug:slug>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path("admin-dashboard/product/list/", views.ProductListView.as_view(), name="product_listedd"),
    #cart
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/', views.CartAddView.as_view(), name='add_cart'),
    path('cart-item-clear/<str:item_id>/', views.ClearCartItemView.as_view(), name='clear_cart_item'),
    path('cart/minus/', views.MinusToCartView.as_view(), name='minus_to_cart'),
    path('cart-clear/', views.ClearCartView.as_view(), name='clear_cart'),
    #wishlist
    path("wishlist/", views.WishlistListView.as_view(), name="wishlist"),
    path("wishlist/add/",views.AddToWishlistView.as_view(),name="add_to_wishlist"),
    path("wishlist/remove/<int:product_id>/",views.RemoveFromWishlistView.as_view(),name="remove_from_wishlist"),
   
]

woodberg/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
app_name = 'web'
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("web.urls", namespace="web")), 
    path("accounts/", include("registration.backends.simple.urls")),
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/web/dashboard/banner_confirm_delete.html
{% extends 'dashboard/base.html' %}
{% block content %}
<h1>Delete Banner</h1>
<p>Are you sure you want to delete "{{ banner.title }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Confirm</button>
</form>
<a href="{% url 'dashboard:banner_list' %}">Cancel</a>
{% endblock %}

templates/web/dashboard/banner_list.html
{% extends 'web/dashboard/base.html' %}
{% block content %}
{% load static %}
<div class="relative min-h-screen group-data-[sidebar-size=sm]:min-h-sm">
  
    <div class="group-data-[sidebar-size=lg]:ltr:md:ml-vertical-menu group-data-[sidebar-size=lg]:rtl:md:mr-vertical-menu group-data-[sidebar-size=md]:ltr:ml-vertical-menu-md group-data-[sidebar-size=md]:rtl:mr-vertical-menu-md group-data-[sidebar-size=sm]:ltr:ml-vertical-menu-sm group-data-[sidebar-size=sm]:rtl:mr-vertical-menu-sm pt-[calc(theme('spacing.header')_*_1)] pb-[calc(theme('spacing.header')_*_0.8)] px-4 group-data-[navbar=bordered]:pt-[calc(theme('spacing.header')_*_1.3)] group-data-[navbar=hidden]:pt-0 group-data-[layout=horizontal]:mx-auto group-data-[layout=horizontal]:max-w-screen-2xl group-data-[layout=horizontal]:px-0 group-data-[layout=horizontal]:group-data-[sidebar-size=lg]:ltr:md:ml-auto group-data-[layout=horizontal]:group-data-[sidebar-size=lg]:rtl:md:mr-auto group-data-[layout=horizontal]:md:pt-[calc(theme('spacing.header')_*_1.6)] group-data-[layout=horizontal]:px-3 group-data-[layout=horizontal]:group-data-[navbar=hidden]:pt-[calc(theme('spacing.header')_*_0.9)]">        
      <div class="container-fluid group-data-[content=boxed]:max-w-boxed mx-auto">

        <h1 class="py-5"></h1>
        <form action="#!" class="mb-5">
            <div class="grid grid-cols-1 gap-5 lg:grid-cols-12">
              
              <div class="lg:col-span-3 lg:col-start-10">
                <div class="flex gap-2 lg:justify-end">
                  <a href="{% url 'web:banner_create' %}">
                    <button data-modal-target="addUserModal" type="button" class="text-white btn bg-custom-500 border-custom-500 hover:text-white hover:bg-custom-600 hover:border-custom-600 focus:text-white focus:bg-custom-600 focus:border-custom-600 focus:ring focus:ring-custom-100 active:text-white active:bg-custom-600 active:border-custom-600 active:ring active:ring-custom-100 dark:ring-custom-400/20"><i data-lucide="plus" class="inline-block size-4"></i> <span class="align-middle">Add banner</span></button>
                  </a>
                </div>
              </div>
            </div>
          </form>
       
      </div>
    </div>

</div>
{% endblock %}
    

templates/web/dashboard/product_confirm_delete.html
{% extends 'web/dashboard/base.html' %}
{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'web/asset/css/form.css' %}">
<div class="relative min-h-screen group-data-[sidebar-size=sm]:min-h-sm">

    <div
        class="group-data-[sidebar-size=lg]:ltr:md:ml-vertical-menu group-data-[sidebar-size=lg]:rtl:md:mr-vertical-menu group-data-[sidebar-size=md]:ltr:ml-vertical-menu-md group-data-[sidebar-size=md]:rtl:mr-vertical-menu-md group-data-[sidebar-size=sm]:ltr:ml-vertical-menu-sm group-data-[sidebar-size=sm]:rtl:mr-vertical-menu-sm pt-[calc(theme('spacing.header')_*_1)] pb-[calc(theme('spacing.header')_*_0.8)] px-4 group-data-[navbar=bordered]:pt-[calc(theme('spacing.header')_*_1.3)] group-data-[navbar=hidden]:pt-0 group-data-[layout=horizontal]:mx-auto group-data-[layout=horizontal]:max-w-screen-2xl group-data-[layout=horizontal]:px-0 group-data-[layout=horizontal]:group-data-[sidebar-size=lg]:ltr:md:ml-auto group-data-[layout=horizontal]:group-data-[sidebar-size=lg]:rtl:md:mr-auto group-data-[layout=horizontal]:md:pt-[calc(theme('spacing.header')_*_1.6)] group-data-[layout=horizontal]:px-3 group-data-[layout=horizontal]:group-data-[navbar=hidden]:pt-[calc(theme('spacing.header')_*_0.9)]">
        <div class="container-fluid group-data-[content=boxed]:max-w-boxed mx-auto">

            <h1>Delete Product</h1>
            <p>Are you sure you want to delete "{{ product.name }}"?</p>
            <form method="post">
                {% csrf_token %}
                <button type="submit">Yes, delete</button>
                <a href="{% url 'web:product_list' %}">Cancel</a>
            </form>







        </div>
    </div>
</div>

{% endblock %}

templates/web/dashboard/product_create.html
{% comment %} {% extends "web/dashboard/base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static "web/asset/css/addform.css" %}">
<div class="relative min-h-screen group-data-[sidebar-size=sm]:min-h-sm">

    <div
        class="group-data-[sidebar-size=lg]:ltr:md:ml-vertical-menu group-data-[sidebar-size=lg]:rtl:md:mr-vertical-menu group-data-[sidebar-size=md]:ltr:ml-vertical-menu-md group-data-[sidebar-size=md]:rtl:mr-vertical-menu-md group-data-[sidebar-size=sm]:ltr:ml-vertical-menu-sm group-data-[sidebar-size=sm]:rtl:mr-vertical-menu-sm pt-[calc(theme('spacing.header')_*_1)] pb-[calc(theme('spacing.header')_*_0.8)] px-4 group-data-[navbar=bordered]:pt-[calc(theme('spacing.header')_*_1.3)] group-data-[navbar=hidden]:pt-0 group-data-[layout=horizontal]:mx-auto group-data-[layout=horizontal]:max-w-screen-2xl group-data-[layout=horizontal]:px-0 group-data-[layout=horizontal]:group-data-[sidebar-size=lg]:ltr:md:ml-auto group-data-[layout=horizontal]:group-data-[sidebar-size=lg]:rtl:md:mr-auto group-data-[layout=horizontal]:md:pt-[calc(theme('spacing.header')_*_1.6)] group-data-[layout=horizontal]:px-3 group-data-[layout=horizontal]:group-data-[navbar=hidden]:pt-[calc(theme('spacing.header')_*_0.9)]">
        <div class="container-fluid group-data-[content=boxed]:max-w-boxed mx-auto">


            
            
            <h1>{{ form.instance.pk|yesno:"Edit Banner,Create New Banner" }}</h1>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="buttonF">Save</button>
            </form>
            


        </div>
    </div>
</div> {% endcomment %}


{% endblock %}

templates/web/dashboard/product_list.html
{% extends "web/dashboard/base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static "web/asset/css/addform.css" %}">
<div class="relative min-h-screen group-data-[sidebar-size=sm]:min-h-sm">

    <div class="group-data-[sidebar-size=lg]:ltr:md:ml-vertical-menu group-data-[sidebar-size=lg]:rtl:md:mr-vertical-menu group-data-[sidebar-size=md]:ltr:ml-vertical-menu-md group-data-[sidebar-size=md]:rtl:mr-vertical-menu-md group-data-[sidebar-size=sm]:ltr:ml-vertical-menu-sm group-data-[sidebar-size=sm]:rtl:mr-vertical-menu-sm pt-[calc(theme('spacing.header')_*_1)] pb-[calc(theme('spacing.header')_*_0.8)] px-4 group-data-[navbar=bordered]:pt-[calc(theme('spacing.header')_*_1.3)] group-data-[navbar=hidden]:pt-0 group-data-[layout=horizontal]:mx-auto group-data-[layout=horizontal]:max-w-screen-2xl group-data-[layout=horizontal]:px-0 group-data-[layout=horizontal]:group-data-[sidebar-size=lg]:ltr:md:ml-auto group-data-[layout=horizontal]:group-data-[sidebar-size=lg]:rtl:md:mr-auto group-data-[layout=horizontal]:md:pt-[calc(theme('spacing.header')_*_1.6)] group-data-[layout=horizontal]:px-3 group-data-[layout=horizontal]:group-data-[navbar=hidden]:pt-[calc(theme('spacing.header')_*_0.9)]">
        <div class="container-fluid group-data-[content=boxed]:max-w-boxed mx-auto">

            <h1 class="py-5"></h1>
            <form action="#!" class="mb-5">
                <div class="grid grid-cols-1 gap-5 lg:grid-cols-12">
                  
                  <div class="lg:col-span-3 lg:col-start-10">
                    <div class="flex gap-2 lg:justify-end">
                      <a href="{% url 'web:add_product' %}">
                        <button data-modal-target="addUserModal" type="button" class="text-white btn bg-custom-500 border-custom-500 hover:text-white hover:bg-custom-600 hover:border-custom-600 focus:text-white focus:bg-custom-600 focus:border-custom-600 focus:ring focus:ring-custom-100 active:text-white active:bg-custom-600 active:border-custom-600 active:ring active:ring-custom-100 dark:ring-custom-400/20"><i data-lucide="plus" class="inline-block size-4"></i> <span class="align-middle">Add Product</span></button>
                      </a>
                    </div>
                  </div>
                </div>
              </form>
           

        </div>
    </div>
</div>
<div class="!pt-1 card-body">
    <div class="overflow-x-auto">
        <table class="w-full whitespace-nowrap" id="productTable">
            <thead class="ltr:text-left rtl:text-right bg-slate-100 dark:bg-zink-600">
                <tr>
                    <th class="px-3.5 py-2.5 font-semibold border-b border-slate-200 dark:border-zink-500 sort product_code" data-sort="product_code">Product Code</th>
                    <th class="px-3.5 py-2.5 font-semibold border-b border-slate-200 dark:border-zink-500 sort product_name" data-sort="product_name">Product Name</th>
                    <th class="px-3.5 py-2.5 font-semibold border-b border-slate-200 dark:border-zink-500 sort category" data-sort="category">Category</th>
                    <th class="px-3.5 py-2.5 font-semibold border-b border-slate-200 dark:border-zink-500 sort price" data-sort="price">Price</th>
                    <th class="px-3.5 py-2.5 font-semibold border-b border-slate-200 dark:border-zink-500 sort stock" data-sort="stock">Stock</th>
                    <th class="px-3.5 py-2.5 font-semibold border-b border-slate-200 dark:border-zink-500 sort revenue" data-sort="revenue">Revenue</th>
                    <th class="px-3.5 py-2.5 font-semibold border-b border-slate-200 dark:border-zink-500 sort status" data-sort="status">Status</th>
                    <th class="px-3.5 py-2.5 font-semibold border-b border-slate-200 dark:border-zink-500 action">Actions</th>
                </tr>
            </thead>
            <tbody class="list">
                <tr>
                    <td class="px-3.5 py-2.5 border-y border-slate-200 dark:border-zink-500">
                        <a href="#!" class="transition-all duration-150 ease-linear product_code text-custom-500 hover:text-custom-600">#TAD-232100071</a>
                    </td>
                    <td class="px-3.5 py-2.5 border-y border-slate-200 dark:border-zink-500 product_name">
                        <a href="apps-ecommerce-product-overview.html" class="flex items-center gap-2">
                            <img src="assets/images/img-012.png" alt="Product images" class="h-6">
                            <h6 class="product_name">Smartest Printed T-shirt</h6>
                        </a>
                    </td>
                    <td class="px-3.5 py-2.5 border-y border-slate-200 dark:border-zink-500 category">
                        <span class="category px-2.5 py-0.5 text-xs inline-block font-medium rounded border bg-slate-100 border-slate-200 text-slate-500 dark:bg-slate-500/20 dark:border-slate-500/20 dark:text-zink-200">Fashion</span>
                    </td>
                    <td class="px-3.5 py-2.5 border-y border-slate-200 dark:border-zink-500 price">$79.99</td>
                    <td class="px-3.5 py-2.5 border-y border-slate-200 dark:border-zink-500 stock">500</td>
                    <td class="px-3.5 py-2.5 border-y border-slate-200 dark:border-zink-500 revenue">$24,365</td>
                    <td class="px-3.5 py-2.5 border-y border-slate-200 dark:border-zink-500 status">
                        <span class="status px-2.5 py-0.5 inline-block text-xs font-medium rounded border bg-orange-100 border-transparent text-orange-500 dark:bg-orange-500/20 dark:border-transparent">Scheduled</span>
                    </td>
                    <td class="px-3.5 py-2.5 border-y border-slate-200 dark:border-zink-500 action">
                        <div class="relative dropdown">
                            <button class="flex items-center justify-center size-[30px] dropdown-toggle p-0 text-slate-500 btn bg-slate-100 hover:text-white hover:bg-slate-600 focus:text-white focus:bg-slate-600 focus:ring focus:ring-slate-100 active:text-white active:bg-slate-600 active:ring active:ring-slate-100 dark:bg-slate-500/20 dark:text-slate-400 dark:hover:bg-slate-500 dark:hover:text-white dark:focus:bg-slate-500 dark:focus:text-white dark:active:bg-slate-500 dark:active:text-white dark:ring-slate-400/20" id="productAction1" data-bs-toggle="dropdown"><i data-lucide="more-horizontal" class="size-3"></i></button>
                            <ul class="absolute z-50 hidden py-2 mt-1 ltr:text-left rtl:text-right list-none bg-white rounded-md shadow-md dropdown-menu min-w-[10rem] dark:bg-zink-600" aria-labelledby="productAction1">
                                <li>
                                    <a class="block px-4 py-1.5 text-base transition-all duration-200 ease-linear text-slate-600 dropdown-item hover:bg-slate-100 hover:text-slate-500 focus:bg-slate-100 focus:text-slate-500 dark:text-zink-100 dark:hover:bg-zink-500 dark:hover:text-zink-200 dark:focus:bg-zink-500 dark:focus:text-zink-200" href="apps-ecommerce-product-overview.html"><i data-lucide="eye" class="inline-block size-3 ltr:mr-1 rtl:ml-1"></i> <span class="align-middle">Overview</span></a>
                                </li>
                                <li>
                                    <a class="block px-4 py-1.5 text-base transition-all duration-200 ease-linear text-slate-600 dropdown-item hover:bg-slate-100 hover:text-slate-500 focus:bg-slate-100 focus:text-slate-500 dark:text-zink-100 dark:hover:bg-zink-500 dark:hover:text-zink-200 dark:focus:bg-zink-500 dark:focus:text-zink-200" href="apps-ecommerce-product-create.html"><i data-lucide="file-edit" class="inline-block size-3 ltr:mr-1 rtl:ml-1"></i> <span class="align-middle">Edit</span></a>
                                </li>
                                <li>
                                    <a data-modal-target="deleteModal" class="block px-4 py-1.5 text-base transition-all duration-200 ease-linear text-slate-600 dropdown-item hover:bg-slate-100 hover:text-slate-500 focus:bg-slate-100 focus:text-slate-500 dark:text-zink-100 dark:hover:bg-zink-500 dark:hover:text-zink-200 dark:focus:bg-zink-500 dark:focus:text-zink-200" href="#!"><i data-lucide="trash-2" class="inline-block size-3 ltr:mr-1 rtl:ml-1"></i> <span class="align-middle">Delete</span></a>
                                </li>
                            </ul>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="noresult" style="display: none">
            <div class="py-6 text-center">
                <i data-lucide="search" class="w-6 h-6 mx-auto mb-3 text-sky-500 fill-sky-100 dark:fill-sky-500/20"></i>
                <h5 class="mt-2 mb-1">Sorry! No Result Found</h5>
                <p class="mb-0 text-slate-500 dark:text-zink-200">We've searched more than 199+ product We did not find any product for you search.</p>
            </div>
        </div>
    </div>

    <div class="flex flex-col items-center gap-4 px-4 mt-4 md:flex-row" id="pagination-element">
        <div class="grow">
            <p class="text-slate-500 dark:text-zink-200">Showing <b class="showing">10</b> of <b class="total-records">38</b> Results</p>
        </div>
    
        <div class="col-sm-auto mt-sm-0">
            <div class="flex gap-2 pagination-wrap justify-content-center">
                <a class="inline-flex items-center justify-center bg-white dark:bg-zink-700 h-8 px-3 transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zink-500 text-slate-500 dark:text-zink-200 hover:text-custom-500 dark:hover:text-custom-500 hover:bg-custom-50 dark:hover:bg-custom-500/10 focus:bg-custom-50 dark:focus:bg-custom-500/10 focus:text-custom-500 dark:focus:text-custom-500 [&.active]:text-custom-500 dark:[&.active]:text-custom-500 [&.active]:bg-custom-50 dark:[&.active]:bg-custom-500/10 [&.active]:border-custom-50 dark:[&.active]:border-custom-500/10 [&.active]:hover:text-custom-700 dark:[&.active]:hover:text-custom-700 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zink-300 [&.disabled]:cursor-auto page-item pagination-prev " href="javascript:void(0)">
                    <i class="mr-1 size-4 rtl:rotate-180" data-lucide="chevron-left"></i> Prev
                </a>
                <ul class="flex flex-wrap items-center gap-2 pagination listjs-pagination">
                </ul>
                <a class="inline-flex items-center justify-center bg-white dark:bg-zink-700 h-8 px-3 transition-all duration-150 ease-linear border rounded border-slate-200 dark:border-zink-500 text-slate-500 dark:text-zink-200 hover:text-custom-500 dark:hover:text-custom-500 hover:bg-custom-50 dark:hover:bg-custom-500/10 focus:bg-custom-50 dark:focus:bg-custom-500/10 focus:text-custom-500 dark:focus:text-custom-500 [&.active]:text-custom-500 dark:[&.active]:text-custom-500 [&.active]:bg-custom-50 dark:[&.active]:bg-custom-500/10 [&.active]:border-custom-50 dark:[&.active]:border-custom-500/10 [&.active]:hover:text-custom-700 dark:[&.active]:hover:text-custom-700 [&.disabled]:text-slate-400 dark:[&.disabled]:text-zink-300 [&.disabled]:cursor-auto page-item pagination-next" href="javascript:void(0)">
                    Next <i class="ml-1 size-4 rtl:rotate-180" data-lucide="chevron-right"></i>
                </a>
            </div>
        </div>
    </div>

</div>


{% endblock %}